import { GetSpeciesDataByName,  GetSpanishName } from "./PokemonSpeciesData";

/**
 * Devuelve un valor entre 1 y 6 referente al "valor de frecuencia"
 * @param dexNum 
 */
export const GetFrequencyByDexNum = (dexNum) => {
    for (let i = 0 ; i < pokemonFrequencies.length ; i++) {
        const foundPokemon = pokemonFrequencies[i].find(pokemon => pokemon.dexNum === dexNum);

        if (foundPokemon) {
            return i + 1;
        }
    }
    return 0;
}


/**
 * Devuelve un valor entre 1 y 6 referente al "valor de frecuencia"
 * @param name 
 */
export const GetFrequencyByName = (name) => {
    for (let i = 0 ; i < pokemonFrequencies.length ; i++) {
        const foundPokemon = pokemonFrequencies[i].find(pokemon => pokemon.name === name);

        if (foundPokemon) {
            return i + 1;
        }
    }
    return 0;
}

/**
 * Devuelve un valor entre 1 y 6 referente al "valor de frecuencia"
 * @param data 
 */
export const GetFrequencyAsync = async (data) => {
    try {
        const poke = await GetSpeciesDataByName(data);
        const realName = GetSpanishName(poke);
        return GetFrequencyByName(realName);
    } catch (error) {
        console.error("ERROR GetFrequencyAsync: " + error)
        return null;
    }
}

let pokemonFrequencies = [
        [
            {"name": "Caterpie"},
            {"name": "Metapod"},
            {"name": "Butterfree"},
            {"name": "Weedle"},
            {"name": "Kakuna"},
            {"name": "Beedrill"},
            {"name": "Pidgey"},
            {"name": "Pidgeotto"},
            {"name": "Pidgeot"},
            {"name": "Rattata"},
            {"name": "Raticate"},
            {"name": "Spearow"},
            {"name": "Fearow"},
            {"name": "Ekans"},
            {"name": "Arbok"},
            {"name": "Pikachu"},
            {"name": "Raichu"},
            {"name": "Sandshrew"},
            {"name": "Sandslash"},
            {"name": "Nidoran♀"},
            {"name": "Nidorina"},
            {"name": "Nidoran♂"},
            {"name": "Nidorino"},
            {"name": "Clefairy"},
            {"name": "Clefable"},
            {"name": "Vulpix"},
            {"name": "Ninetales"},
            {"name": "Jigglypuff"},
            {"name": "Wigglytuff"},
            {"name": "Zubat"},
            {"name": "Golbat"},
            {"name": "Oddish"},
            {"name": "Gloom"},
            {"name": "Vileplume"},
            {"name": "Paras"},
            {"name": "Parasect"},
            {"name": "Venonat"},
            {"name": "Venomoth"},
            {"name": "Diglett"},
            {"name": "Dugtrio"},
            {"name": "Meowth"},
            {"name": "Persian"},
            {"name": "Psyduck"},
            {"name": "Golduck"},
            {"name": "Mankey"},
            {"name": "Primeape"},
            {"name": "Growlithe"},
            {"name": "Poliwag"},
            {"name": "Poliwhirl"},
            {"name": "Poliwrath"},
            {"name": "Abra"},
            {"name": "Kadabra"},
            {"name": "Alakazam"},
            {"name": "Machop"},
            {"name": "Machoke"},
            {"name": "Machamp"},
            {"name": "Bellsprout"},
            {"name": "Weepinbell"},
            {"name": "Victreebel"},
            {"name": "Tentacool"},
            {"name": "Tentacruel"},
            {"name": "Geodude"},
            {"name": "Graveler"},
            {"name": "Golem"},
            {"name": "Ponyta"},
            {"name": "Rapidash"},
            {"name": "Slowpoke"},
            {"name": "Slowbro"},
            {"name": "Magnemite"},
            {"name": "Magneton"},
            {"name": "Farfetch'd"},
            {"name": "Doduo"},
            {"name": "Dodrio"},
            {"name": "Seel"},
            {"name": "Dewgong"},
            {"name": "Grimer"},
            {"name": "Muk"},
            {"name": "Shellder"},
            {"name": "Cloyster"},
            {"name": "Gastly"},
            {"name": "Haunter"},
            {"name": "Gengar"},
            {"name": "Onix"},
            {"name": "Drowzee"},
            {"name": "Hypno"},
            {"name": "Krabby"},
            {"name": "Kingler"},
            {"name": "Voltorb"},
            {"name": "Electrode"},
            {"name": "Exeggcute"},
            {"name": "Exeggutor"},
            {"name": "Cubone"},
            {"name": "Marowak"},
            {"name": "Hitmonlee"},
            {"name": "Hitmonchan"},
            {"name": "Lickitung"},
            {"name": "Koffing"},
            {"name": "Weezing"},
            {"name": "Rhyhorn"},
            {"name": "Rhydon"},
            {"name": "Chansey"},
            {"name": "Tangela"},
            {"name": "Kangaskhan"},
            {"name": "Horsea"},
            {"name": "Seadra"},
            {"name": "Goldeen"},
            {"name": "Seaking"},
            {"name": "Staryu"},
            {"name": "Starmie"},
            {"name": "Mr. Mime"},
            {"name": "Scyther"},
            {"name": "Jynx"},
            {"name": "Electabuzz"},
            {"name": "Magmar"},
            {"name": "Pinsir"},
            {"name": "Tauros"},
            {"name": "Magikarp"},
            {"name": "Gyarados"},
            {"name": "Lapras"},
            {"name": "Ditto"},
            {"name": "Porygon"},
            {"name": "Omanyte"},
            {"name": "Omastar"},
            {"name": "Kabuto"},
            {"name": "Kabutops"},
            {"name": "Aerodactyl"},
            {"name": "Snorlax"},
            {"name": "Articuno"},
            {"name": "Zapdos"},
            {"name": "Moltres"},
            {"name": "Sentret"},
            {"name": "Furret"},
            {"name": "Hoothoot"},
            {"name": "Noctowl"},
            {"name": "Ledyba"},
            {"name": "Ledian"},
            {"name": "Spinarak"},
            {"name": "Ariados"},
            {"name": "Crobat"},
            {"name": "Chinchou"},
            {"name": "Lanturn"},
            {"name": "Pichu"},
            {"name": "Cleffa"},
            {"name": "Igglybuff"},
            {"name": "Togepi"},
            {"name": "Togetic"},
            {"name": "Natu"},
            {"name": "Xatu"},
            {"name": "Mareep"},
            {"name": "Flaaffy"},
            {"name": "Ampharos"},
            {"name": "Bellossom"},
            {"name": "Marill"},
            {"name": "Azumarill"},
            {"name": "Sudowoodo"},
            {"name": "Politoed"},
            {"name": "Hoppip"},
            {"name": "Skiploom"},
            {"name": "Jumpluff"},
            {"name": "Aipom"},
            {"name": "Sunkern"},
            {"name": "Sunflora"},
            {"name": "Yanma"},
            {"name": "Wooper"},
            {"name": "Quagsire"},
            {"name": "Murkrow"},
            {"name": "Slowking"},
            {"name": "Misdreavus"},
            {"name": "Unown"},
            {"name": "Wobbuffet"},
            {"name": "Girafarig"},
            {"name": "Pineco"},
            {"name": "Forretress"},
            {"name": "Dunsparce"},
            {"name": "Gligar"},
            {"name": "Steelix"},
            {"name": "Snubbull"},
            {"name": "Granbull"},
            {"name": "Qwilfish"},
            {"name": "Scizor"},
            {"name": "Shuckle"},
            {"name": "Heracross"},
            {"name": "Sneasel"},
            {"name": "Teddiursa"},
            {"name": "Ursaring"},
            {"name": "Slugma"},
            {"name": "Magcargo"},
            {"name": "Swinub"},
            {"name": "Piloswine"},
            {"name": "Corsola"},
            {"name": "Remoraid"},
            {"name": "Octillery"},
            {"name": "Delibird"},
            {"name": "Mantine"},
            {"name": "Skarmory"},
            {"name": "Houndour"},
            {"name": "Houndoom"},
            {"name": "Kingdra"},
            {"name": "Phanpy"},
            {"name": "Donphan"},
            {"name": "Porygon2"},
            {"name": "Stantler"},
            {"name": "Smeargle"},
            {"name": "Tyrogue"},
            {"name": "Hitmontop"},
            {"name": "Smoochum"},
            {"name": "Elekid"},
            {"name": "Magby"},
            {"name": "Miltank"},
            {"name": "Blissey"},
            {"name": "Poochyena"},
            {"name": "Mightyena"},
            {"name": "Zigzagoon"},
            {"name": "Linoone"},
            {"name": "Wurmple"},
            {"name": "Silcoon"},
            {"name": "Beautifly"},
            {"name": "Cascoon"},
            {"name": "Dustox"},
            {"name": "Lotad"},
            {"name": "Lombre"},
            {"name": "Ludicolo"},
            {"name": "Seedot"},
            {"name": "Nuzleaf"},
            {"name": "Shiftry"},
            {"name": "Taillow"},
            {"name": "Swellow"},
            {"name": "Wingull"},
            {"name": "Pelipper"},
            {"name": "Ralts"},
            {"name": "Kirlia"},
            {"name": "Gardevoir"},
            {"name": "Surskit"},
            {"name": "Masquerain"},
            {"name": "Shroomish"},
            {"name": "Breloom"},
            {"name": "Slakoth"},
            {"name": "Vigoroth"},
            {"name": "Slaking"},
            {"name": "Nincada"},
            {"name": "Ninjask"},
            {"name": "Shedinja"},
            {"name": "Whismur"},
            {"name": "Loudred"},
            {"name": "Exploud"},
            {"name": "Makuhita"},
            {"name": "Hariyama"},
            {"name": "Azurill"},
            {"name": "Skitty"},
            {"name": "Delcatty"},
            {"name": "Sableye"},
            {"name": "Mawile"},
            {"name": "Aron"},
            {"name": "Lairon"},
            {"name": "Aggron"},
            {"name": "Meditite"},
            {"name": "Medicham"},
            {"name": "Electrike"},
            {"name": "Manectric"},
            {"name": "Plusle"},
            {"name": "Minun"},
            {"name": "Volbeat"},
            {"name": "Illumise"},
            {"name": "Roselia"},
            {"name": "Gulpin"},
            {"name": "Swalot"},
            {"name": "Carvanha"},
            {"name": "Sharpedo"},
            {"name": "Wailmer"},
            {"name": "Wailord"},
            {"name": "Numel"},
            {"name": "Camerupt"},
            {"name": "Torkoal"},
            {"name": "Spoink"},
            {"name": "Grumpig"},
            {"name": "Spinda"},
            {"name": "Trapinch"},
            {"name": "Vibrava"},
            {"name": "Flygon"},
            {"name": "Cacnea"},
            {"name": "Cacturne"},
            {"name": "Swablu"},
            {"name": "Altaria"},
            {"name": "Zangoose"},
            {"name": "Seviper"},
            {"name": "Lunatone"},
            {"name": "Solrock"},
            {"name": "Barboach"},
            {"name": "Whiscash"},
            {"name": "Corphish"},
            {"name": "Crawdaunt"},
            {"name": "Baltoy"},
            {"name": "Claydol"},
            {"name": "Lileep"},
            {"name": "Cradily"},
            {"name": "Anorith"},
            {"name": "Armaldo"},
            {"name": "Feebas"},
            {"name": "Milotic"},
            {"name": "Castform"},
            {"name": "Kecleon"},
            {"name": "Shuppet"},
            {"name": "Banette"},
            {"name": "Duskull"},
            {"name": "Dusclops"},
            {"name": "Tropius"},
            {"name": "Chimecho"},
            {"name": "Absol"},
            {"name": "Wynaut"},
            {"name": "Snorunt"},
            {"name": "Glalie"},
            {"name": "Spheal"},
            {"name": "Sealeo"},
            {"name": "Walrein"},
            {"name": "Clamperl"},
            {"name": "Huntail"},
            {"name": "Gorebyss"},
            {"name": "Relicanth"},
            {"name": "Luvdisc"},
            
            {"name": "Starly"},
            {"name": "Staravia"},
            {"name": "Staraptor"},
            {"name": "Bidoof"},
            {"name": "Bibarel"},
            {"name": "Kricketot"},
            {"name": "Kricketune"},
            {"name": "Shinx"},
            {"name": "Luxio"},
            {"name": "Luxray"},
            {"name": "Budew"},
            {"name": "Roserade"},
            {"name": "Cranidos"},
            {"name": "Rampardos"},
            {"name": "Shieldon"},
            {"name": "Bastiodon"},
            {"name": "Burmy"},
            {"name": "Wormadam"},
            {"name": "Mothim"},
            {"name": "Combee"},
            {"name": "Vespiquen"},
            {"name": "Pachirisu"},
            {"name": "Buizel"},
            {"name": "Floatzel"},
            {"name": "Cherubi"},
            {"name": "Cherrim"},
            {"name": "Shellos"},
            {"name": "Gastrodon"},
            {"name": "Ambipom"},
            {"name": "Drifloon"},
            {"name": "Drifblim"},
            {"name": "Buneary"},
            {"name": "Lopunny"},
            {"name": "Mismagius"},
            {"name": "Honchkrow"},
            {"name": "Glameow"},
            {"name": "Purugly"},
            {"name": "Chingling"},
            {"name": "Stunky"},
            {"name": "Skuntank"},
            {"name": "Bronzor"},
            {"name": "Bronzong"},
            {"name": "Bonsly"},
            {"name": "Mime Jr."},
            {"name": "Happiny"},
            {"name": "Chatot"},
            {"name": "Spiritomb"},
            {"name": "Munchlax"},
            {"name": "Riolu"},
            {"name": "Lucario"},
            {"name": "Hippopotas"},
            {"name": "Hippowdon"},
            {"name": "Skorupi"},
            {"name": "Drapion"},
            {"name": "Croagunk"},
            {"name": "Toxicroak"},
            {"name": "Carnivine"},
            {"name": "Finneon"},
            {"name": "Lumineon"},
            {"name": "Mantyke"},
            {"name": "Snover"},
            {"name": "Abomasnow"},
            {"name": "Rotom"},
            
            {"name": "Patrat"},
            {"name": "Watchog"},
            {"name": "Lillipup"},
            {"name": "Herdier"},
            {"name": "Stoutland"},
            {"name": "Purrloin"},
            {"name": "Liepard"},
            {"name": "Pansage"},
            {"name": "Simisage"},
            {"name": "Pansear"},
            {"name": "Simisear"},
            {"name": "Panpour"},
            {"name": "Simipour"},
            {"name": "Munna"},
            {"name": "Musharna"},
            {"name": "Pidove"},
            {"name": "Tranquill"},
            {"name": "Unfezant"},
            {"name": "Blitzle"},
            {"name": "Zebstrika"},
            {"name": "Roggenrola"},
            {"name": "Boldore"},
            {"name": "Gigalith"},
            {"name": "Woobat"},
            {"name": "Swoobat"},
            {"name": "Drilbur"},
            {"name": "Excadrill"},
            {"name": "Audino"},
            {"name": "Timburr"},
            {"name": "Gurdurr"},
            {"name": "Conkeldurr"},
            {"name": "Tympole"},
            {"name": "Palpitoad"},
            {"name": "Seismitoad"},
            {"name": "Throh"},
            {"name": "Sawk"},
            {"name": "Sewaddle"},
            {"name": "Swadloon"},
            {"name": "Leavanny"},
            {"name": "Venipede"},
            {"name": "Whirlipede"},
            {"name": "Scolipede"},
            {"name": "Cottonee"},
            {"name": "Whimsicott"},
            {"name": "Petilil"},
            {"name": "Lilligant"},
            {"name": "Basculin"},
            {"name": "Sandile"},
            {"name": "Krokorok"},
            {"name": "Krookodile"},
            {"name": "Darumaka"},
            {"name": "Darmanitan"},
            {"name": "Maractus"},
            {"name": "Dwebble"},
            {"name": "Crustle"},
            {"name": "Scraggy"},
            {"name": "Scrafty"},
            {"name": "Sigilyph"},
            {"name": "Yamask"},
            {"name": "Cofagrigus"},
            {"name": "Tirtouga"},
            {"name": "Carracosta"},
            {"name": "Archen"},
            {"name": "Archeops"},
            {"name": "Trubbish"},
            {"name": "Garbodor"},
            {"name": "Zorua"},
            {"name": "Zoroark"},
            {"name": "Minccino"},
            {"name": "Cinccino"},
            {"name": "Gothita"},
            {"name": "Gothorita"},
            {"name": "Gothitelle"},
            {"name": "Solosis"},
            {"name": "Duosion"},
            {"name": "Reuniclus"},
            {"name": "Ducklett"},
            {"name": "Swanna"},
            {"name": "Vanillite"},
            {"name": "Vanillish"},
            {"name": "Vanilluxe"},
            {"name": "Deerling"},
            {"name": "Sawsbuck"},
            {"name": "Emolga"},
            {"name": "Karrablast"},
            {"name": "Escavalier"},
            {"name": "Foongus"},
            {"name": "Amoonguss"},
            {"name": "Frillish"},
            {"name": "Jellicent"},
            {"name": "Alomomola"},
            {"name": "Joltik"},
            {"name": "Galvantula"},
            {"name": "Ferroseed"},
            {"name": "Ferrothorn"},
            {"name": "Klink"},
            {"name": "Klang"},
            {"name": "Klinklang"},
            {"name": "Tynamo"},
            {"name": "Eelektrik"},
            {"name": "Eelektross"},
            {"name": "Elgyem"},
            {"name": "Beheeyem"},
            {"name": "Cubchoo"},
            {"name": "Beartic"},
            {"name": "Cryogonal"},
            {"name": "Shelmet"},
            {"name": "Accelgor"},
            {"name": "Stunfisk"},
            {"name": "Mienfoo"},
            {"name": "Mienshao"},
            {"name": "Druddigon"},
            {"name": "Golett"},
            {"name": "Golurk"},
            {"name": "Pawniard"},
            {"name": "Bisharp"},
            {"name": "Bouffalant"},
            {"name": "Rufflet"},
            {"name": "Braviary"},
            {"name": "Vullaby"},
            {"name": "Mandibuzz"},
            {"name": "Heatmor"},
            {"name": "Durant"},
            
            {"name": "Bunnelby"},
            {"name": "Diggersby"},
            {"name": "Fletchling"},
            {"name": "Fletchinder"},
            {"name": "Talonflame"},
            {"name": "Scatterbug"},
            {"name": "Spewpa"},
            {"name": "Vivillon"},
            {"name": "Litleo"},
            {"name": "Pyroar"},
            {"name": "Flabébé"},
            {"name": "Floette"},
            {"name": "Florges"},
            {"name": "Skiddo"},
            {"name": "Gogoat"},
            {"name": "Pancham"},
            {"name": "Pangoro"},
            {"name": "Furfrou"},
            {"name": "Espurr"},
            {"name": "Meowstic"},
            {"name": "Honedge"},
            {"name": "Doublade"},
            {"name": "Aegislash"},
            {"name": "Spritzee"},
            {"name": "Aromatisse"},
            {"name": "Swirlix"},
            {"name": "Slurpuff"},
            {"name": "Inkay"},
            {"name": "Malamar"},
            {"name": "Binacle"},
            {"name": "Barbaracle"},
            {"name": "Skrelp"},
            {"name": "Dragalge"},
            {"name": "Clauncher"},
            {"name": "Clawitzer"},
            {"name": "Helioptile"},
            {"name": "Heliolisk"},
            {"name": "Tyrunt"},
            {"name": "Tyrantrum"},
            {"name": "Amaura"},
            {"name": "Aurorus"},
            {"name": "Dedenne"},
            {"name": "Carbink"},
            {"name": "Klefki"},
            {"name": "Phantump"},
            {"name": "Trevenant"},
            {"name": "Pumpkaboo"},
            {"name": "Gourgeist"},
            {"name": "Bergmite"},
            {"name": "Avalugg"},
            {"name": "Pikipek"},
            {"name": "Trumbeak"},
            {"name": "Toucannon"},
            {"name": "Yungoos"},
            {"name": "Gumshoos"},
            {"name": "Grubbin"},
            {"name": "Charjabug"},
            {"name": "Vikavolt"},
            {"name": "Crabrawler"},
            {"name": "Crabominable"},
            {"name": "Oricorio"},
            {"name": "Cutiefly"},
            {"name": "Ribombee"},
            {"name": "Rockruff"},
            {"name": "Lycanroc"},
            {"name": "Wishiwashi"},
            {"name": "Mareanie"},
            {"name": "Toxapex"},
            {"name": "Mudbray"},
            {"name": "Mudsdale"},
            {"name": "Dewpider"},
            {"name": "Araquanid"},
            {"name": "Fomantis"},
            {"name": "Lurantis"},
            {"name": "Morelull"},
            {"name": "Shiinotic"},
            {"name": "Salandit"},
            {"name": "Salazzle"},
            {"name": "Stufful"},
            {"name": "Bewear"},
            {"name": "Bounsweet"},
            {"name": "Steenee"},
            {"name": "Tsareena"},
            {"name": "Comfey"},
            {"name": "Oranguru"},
            {"name": "Passimian"},
            {"name": "Wimpod"},
            {"name": "Golisopod"},
            {"name": "Sandygast"},
            {"name": "Palossand"},
            {"name": "Pyukumuku"},
            {"name": "Minior"},
            {"name": "Komala"},
            {"name": "Turtonator"},
            {"name": "Togedemaru"},
            {"name": "Mimikyu"},
            {"name": "Bruxish"},
            {"name": "Drampa"},
            {"name": "Dhelmise"},
            {"name": "Skwovet"},
            {"name": "Greedent"},
            {"name": "Rookidee"},
            {"name": "Corvisquire"},
            {"name": "Corviknight"},
            {"name": "Blipbug"},
            {"name": "Dottler"},
            {"name": "Orbeetle"},
            {"name": "Nickit"},
            {"name": "Thievul"},
            {"name": "Gossifleur"},
            {"name": "Eldegoss"},
            {"name": "Wooloo"},
            {"name": "Dubwool"},
            {"name": "Chewtle"},
            {"name": "Drednaw"},
            {"name": "Yamper"},
            {"name": "Boltund"},
            {"name": "Rolycoly"},
            {"name": "Carkol"},
            {"name": "Coalossal"},
            {"name": "Applin"},
            {"name": "Flapple"},
            {"name": "Appletun"},
            {"name": "Silicobra"},
            {"name": "Sandaconda"},
            {"name": "Cramorant"},
            {"name": "Arrokuda"},
            {"name": "Barraskewda"},
            {"name": "Toxel"},
            {"name": "Toxtricity"},
            {"name": "Sizzlipede"},
            {"name": "Centiskorch"},
            {"name": "Clobbopus"},
            {"name": "Grapploct"},
            {"name": "Sinistea"},
            {"name": "Polteageist"},
            {"name": "Hatenna"},
            {"name": "Hattrem"},
            {"name": "Hatterene"},
            {"name": "Impidimp"},
            {"name": "Morgrem"},
            {"name": "Grimmsnarl"},
            {"name": "Obstagoon"},
            {"name": "Perrserker"},
            {"name": "Cursola"},
            {"name": "Sirfetch’d"},
            {"name": "Mr. Rime"},
            {"name": "Runerigus"},
            {"name": "Milcery"},
            {"name": "Alcremie"},
            {"name": "Falinks"},
            {"name": "Pincurchin"},
            {"name": "Snom"},
            {"name": "Frosmoth"},
            {"name": "Stonjourner"},
            {"name": "Eiscue"},
            {"name": "Indeedee"},
            {"name": "Morpeko"},
            {"name": "Cufant"},
            {"name": "Copperajah"},
            {"name": "Wyrdeer"},
            {"name": "Kleavor"},
            {"name": "Ursaluna"},
            {"name": "Basculegion"},
            {"name": "Sneasler"},
            {"name": "Overqwil"},
            {"name": "Lechonk"},
            {"name": "Oinkologne"},
            {"name": "Tarountula"},
            {"name": "Spidops"},
            {"name": "Nymble"},
            {"name": "Lokix"},
            {"name": "Pawmi"},
            {"name": "Pawmo"},
            {"name": "Pawmot"},
            {"name": "Tandemaus"},
            {"name": "Maushold"},
            {"name": "Fidough"},
            {"name": "Dachsbun"},
            {"name": "Smoliv"},
            {"name": "Dolliv"},
            {"name": "Arboliva"},
            {"name": "Squawkabilly"},
            {"name": "Nacli"},
            {"name": "Naclstack"},
            {"name": "Garganacl"},
            {"name": "Charcadet"},
            {"name": "Armarouge"},
            {"name": "Ceruledge"},
            {"name": "Tadbulb"},
            {"name": "Bellibolt"},
            {"name": "Wattrel"},
            {"name": "Kilowattrel"},
            {"name": "Maschiff"},
            {"name": "Mabosstiff"},
            {"name": "Shroodle"},
            {"name": "Grafaiai"},
            {"name": "Bramblin"},
            {"name": "Brambleghast"},
            {"name": "Toedscool"},
            {"name": "Toedscruel"},
            {"name": "Klawf"},
            {"name": "Capsakid"},
            {"name": "Scovillain"},
            {"name": "Rellor"},
            {"name": "Rabsca"},
            {"name": "Flittle"},
            {"name": "Espathra"},
            {"name": "Wiglett"},
            {"name": "Wugtrio"},
            {"name": "Bombirdier"},
            {"name": "Finizen"},
            {"name": "Palafin"},
            {"name": "Varoom"},
            {"name": "Revavroom"},
            {"name": "Cyclizar"},
            {"name": "Orthworm"},
            {"name": "Glimmet"},
            {"name": "Glimmora"},
            {"name": "Greavard"},
            {"name": "Houndstone"},
            {"name": "Flamigo"},
            {"name": "Cetoddle"},
            {"name": "Cetitan"},
            {"name": "Veluza"},
            {"name": "Dondozo"},
            {"name": "Tatsugiri"},
            {"name": "Annihilape"},
            {"name": "Clodsire"},
            {"name": "Farigiraf"},
            {"name": "Dudunsparce"},
            {"name": "Gimmighoul"},
            {"name": "Gholdengo"},
            {"name": "Dipplin"},
            {"name": "Poltchageist"},
            {"name": "Sinistcha"},
            {"name": "Hydrapple"},
            
    ],
    /* Tier 2 */ [
    {"name": "Tinkatink", "dexNum": 957},
    {"name": "Nosepass", "dexNum": 299},
    {"name": "Eevee", "dexNum": 133},
    {"name": "Frigibax", "dexNum": 996},
    {"name": "Dreepy", "dexNum": 885},
    {"name": "Jangmo-o", "dexNum": 782},
    {"name": "Grookey", "dexNum": 810},
    {"name": "Scorbunny", "dexNum": 813},
    {"name": "Sobble", "dexNum": 816},
    {"name": "Noibat", "dexNum": 714},
    {"name": "Rowlet", "dexNum": 722},
    {"name": "Litten", "dexNum": 725},
    {"name": "Popplio", "dexNum": 728},
    {"name": "Litwick", "dexNum": 607},
    {"name": "Axew", "dexNum": 610},
    {"name": "Goomy", "dexNum": 704},
    {"name": "Deino", "dexNum": 633},
    {"name": "Fennekin", "dexNum": 653},
    {"name": "Froakie", "dexNum": 656},
    {"name": "Snivy", "dexNum": 495},
    {"name": "Tepig", "dexNum": 498},
    {"name": "Oshawott", "dexNum": 501},
    {"name": "Dratini", "dexNum": 147},
    {"name": "Chikorita", "dexNum": 152},
    {"name": "Cyndaquil", "dexNum": 155},
    {"name": "Totodile", "dexNum": 158},
    {"name": "Chespin", "dexNum": 650},
    {"name": "Bulbasaur", "dexNum": 1},
    {"name": "Squirtle", "dexNum": 7},
    {"name": "Charmander", "dexNum": 4},
    {"name": "Sprigatito", "dexNum": 906},
    {"name": "Fuecoco", "dexNum": 909},
    {"name": "Quaxly", "dexNum": 912},
    {"name": "Larvitar", "dexNum": 246},
    {"name": "Treecko", "dexNum": 252},
    {"name": "Torchic", "dexNum": 255},
    {"name": "Mudkip", "dexNum": 258},
    {"name": "Bagon", "dexNum": 371},
    {"name": "Beldum", "dexNum": 374},
    {"name": "Turtwig", "dexNum": 387},
    {"name": "Chimchar", "dexNum": 390},
    {"name": "Piplup", "dexNum": 393},
    {"name": "Gible", "dexNum": 443}
]
,
    /* Tier 3 */ [
    {"name": "Tinkatuff", "dexNum": null},
    {"name": "Hawlucha", "dexNum": 701},
    {"name": "Tangrowth", "dexNum": 465},
    {"name": "Lickilicky", "dexNum": 463},
    {"name": "Probopass", "dexNum": 476},
    {"name": "Arctibax", "dexNum": 997},
    {"name": "Duraludon", "dexNum": 884},
    {"name": "Drakloak", "dexNum": 886},
    {"name": "Drizzile", "dexNum": 815},
    {"name": "Raboot", "dexNum": 813},
    {"name": "Thwackey", "dexNum": 811},
    {"name": "Hakamo-o", "dexNum": 784},
    {"name": "Brionne", "dexNum": 729},
    {"name": "Torracat", "dexNum": 726},
    {"name": "Dartrix", "dexNum": 723},
    {"name": "Fraxure", "dexNum": 611},
    {"name": "Lampent", "dexNum": 608},
    {"name": "Sliggoo", "dexNum": 705},
    {"name": "Frogadier", "dexNum": 657},
    {"name": "Braixen", "dexNum": 654},
    {"name": "Quilladin", "dexNum": 652},
    {"name": "Larvesta", "dexNum": 636},
    {"name": "Zweilous", "dexNum": 634},
    {"name": "Gabite", "dexNum": 444},
    {"name": "Dewott", "dexNum": 502},
    {"name": "Pignite", "dexNum": 499},
    {"name": "Servine", "dexNum": 496},
    {"name": "Prinplup", "dexNum": 394},
    {"name": "Monferno", "dexNum": 391},
    {"name": "Grotle", "dexNum": 388},
    {"name": "Metang", "dexNum": 375},
    {"name": "Shelgon", "dexNum": 372},
    {"name": "Pupitar", "dexNum": 247},
    {"name": "Marshtomp", "dexNum": 259},
    {"name": "Combusken", "dexNum": 256},
    {"name": "Grovyle", "dexNum": 253},
    {"name": "Floragato", "dexNum": 907},
    {"name": "Crocalor", "dexNum": 909},
    {"name": "Quaxwell", "dexNum": 913},
    {"name": "Dragonair", "dexNum": 148},
    {"name": "Bayleef", "dexNum": 153},
    {"name": "Quilava", "dexNum": 156},
    {"name": "Croconaw", "dexNum": 159},
    {"name": "Arcanine", "dexNum": 59},
    {"name": "Ivysaur", "dexNum": 2},
    {"name": "Charmeleon", "dexNum": 5},
    {"name": "Wartortle", "dexNum": 8}
],

    /* Tier 4 */ [
        
        {"name": "Tinkaton", "dexNum": 959},
    {"name": "Bramaluna", "dexNum": 960},
    {"name": "Ferropaladín", "dexNum": 1006},
    {"name": "Archaludon", "dexNum": 1018},
    {"name": "Sylveon", "dexNum": 700},
    {"name": "Weavile", "dexNum": 461},
    {"name": "Magnezone", "dexNum": 462},
    {"name": "Rhyperior", "dexNum": 464},
    {"name": "Electivire", "dexNum": 466},
    {"name": "Magmortar", "dexNum": 467},
    {"name": "Togekiss", "dexNum": 468},
    {"name": "Yanmega", "dexNum": 469},
    {"name": "Leafeon", "dexNum": 470},
    {"name": "Glaceon", "dexNum": 471},
    {"name": "Gliscor", "dexNum": 472},
    {"name": "Mamoswine", "dexNum": 473},
    {"name": "Porygon-Z", "dexNum": 474},
    {"name": "Gallade", "dexNum": 475},
    {"name": "Dusknoir", "dexNum": 477},
    {"name": "Froslass", "dexNum": 478},
    {"name": "Vaporeon", "dexNum": 134},
    {"name": "Jolteon", "dexNum": 135},
    {"name": "Flareon", "dexNum": 136},
    {"name": "Baxcalibur", "dexNum": 998},
    {"name": "Dracozolt", "dexNum": 880},
    {"name": "Arctozolt", "dexNum": 881},
    {"name": "Dracovish", "dexNum": 882},
    {"name": "Arctovish", "dexNum": 883},
    {"name": "Dragapult", "dexNum": 887},
    {"name": "Inteleon", "dexNum": 818},
    {"name": "Cinderace", "dexNum": 815},
    {"name": "Rillaboom", "dexNum": 812},
    {"name": "Kommo-o", "dexNum": 784},
    {"name": "Noivern", "dexNum": 715},
    {"name": "Decidueye", "dexNum": 724},
    {"name": "Incineroar", "dexNum": 727},
    {"name": "Primarina", "dexNum": 730},
    {"name": "Chandelure", "dexNum": 609},
    {"name": "Haxorus", "dexNum": 612},
    {"name": "Goodra", "dexNum": 706},
    {"name": "Greninja", "dexNum": 658},
    {"name": "Delphox", "dexNum": 655},
    {"name": "Chesnaught", "dexNum": 652},
    {"name": "Volcarona", "dexNum": 637},
    {"name": "Hydreigon", "dexNum": 635},
    {"name": "Garchomp", "dexNum": 445},
    {"name": "Samurott", "dexNum": 503},
    {"name": "Emboar", "dexNum": 500},
    {"name": "Serperior", "dexNum": 497},
    {"name": "Empoleon", "dexNum": 395},
    {"name": "Infernape", "dexNum": 392},
    {"name": "Torterra", "dexNum": 389},
    {"name": "Metagross", "dexNum": 376},
    {"name": "Salamence", "dexNum": 373},
    {"name": "Swampert", "dexNum": 260},
    {"name": "Blaziken", "dexNum": 257},
    {"name": "Sceptile", "dexNum": 254},
    {"name": "Tyranitar", "dexNum": 248},
    {"name": "Quaquaval", "dexNum": 914},
    {"name": "Dragonite", "dexNum": 149},
    {"name": "Meganium", "dexNum": 154},
    {"name": "Typhlosion", "dexNum": 157},
    {"name": "Feraligatr", "dexNum": 160},
    {"name": "Venusaur", "dexNum": 3},
    {"name": "Blastoise", "dexNum": 9},
    {"name": "Meowscarada", "dexNum": 908},
    {"name": "Espeon", "dexNum": 196},
    {"name": "Umbreon", "dexNum": 197},
    {"name": "Charizard", "dexNum": 6},
    {"name": "Skeledirge", "dexNum": 911},
    {"name": "Kingambit", "dexNum": 983},
    {"name": "Colmilargo", "dexNum": 984},
    {"name": "Colagrito", "dexNum": 985},
    {"name": "Furioseta", "dexNum": 986},
    {"name": "Melenaleteo", "dexNum": 987},
    {"name": "Reptalada", "dexNum": 988},
    {"name": "Pelarena", "dexNum": 989},
    {"name": "Ferrodada", "dexNum": 990},
    {"name": "Ferrosaco", "dexNum": 991},
    {"name": "Ferropalmas", "dexNum": 992},
    {"name": "Ferrocuello", "dexNum": 993},
    {"name": "Ferropolilla", "dexNum": 994},
    {"name": "Ferropúas", "dexNum": 995}
    ],
    /* Tier 5 */ [
        {"name": "Okidogi", "dexNum": 1014},
    {"name": "Munkidori", "dexNum": 1015},
    {"name": "Fezandipiti", "dexNum": 1016},
    {"name": "Mewtwo", "dexNum": 150},
    {"name": "Raikou", "dexNum": 243},
    {"name": "Entei", "dexNum": 244},
    {"name": "Suicune", "dexNum": 245},
    {"name": "Lugia", "dexNum": 249},
    {"name": "Ho-oh", "dexNum": 250},
    {"name": "Regirock", "dexNum": 377},
    {"name": "Regice", "dexNum": 378},
    {"name": "Registeel", "dexNum": 379},
    {"name": "Latias", "dexNum": 380},
    {"name": "Latios", "dexNum": 381},
    {"name": "Kyogre", "dexNum": 382},
    {"name": "Groudon", "dexNum": 383},
    {"name": "Rayquaza", "dexNum": 384},
    {"name": "Uxie", "dexNum": 480},
    {"name": "Mesprit", "dexNum": 481},
    {"name": "Azelf", "dexNum": 482},
    {"name": "Dialga", "dexNum": 483},
    {"name": "Palkia", "dexNum": 484},
    {"name": "Heatran", "dexNum": 485},
    {"name": "Regigigas", "dexNum": 486},
    {"name": "Giratina", "dexNum": 487},
    {"name": "Cresselia", "dexNum": 488},
    {"name": "Cobalion", "dexNum": 638},
    {"name": "Terrakion", "dexNum": 639},
    {"name": "Virizion", "dexNum": 640},
    {"name": "Tornadus", "dexNum": 641},
    {"name": "Thundurus", "dexNum": 642},
    {"name": "Reshiram", "dexNum": 643},
    {"name": "Zekrom", "dexNum": 644},
    {"name": "Landorus", "dexNum": 645},
    {"name": "Kyurem", "dexNum": 646},
    {"name": "Xerneas", "dexNum": 716},
    {"name": "Yveltal", "dexNum": 717},
    {"name": "Zygarde", "dexNum": 718},
    {"name": "Código Cero", "dexNum": 772},
    {"name": "Silvally", "dexNum": 773},
    {"name": "Tapu koko", "dexNum": 785},
    {"name": "Tapu lele", "dexNum": 786},
    {"name": "Tapu bulu", "dexNum": 787},
    {"name": "Tapu fini", "dexNum": 788},
    {"name": "Cosmog", "dexNum": 789},
    {"name": "Cosmoem", "dexNum": 790},
    {"name": "Solgaleo", "dexNum": 791},
    {"name": "Lunala", "dexNum": 792},
    {"name": "Nihilego", "dexNum": 793},
    {"name": "Buzzwole", "dexNum": 794},
    {"name": "Pheromosa", "dexNum": 795},
    {"name": "Xurkitree", "dexNum": 796},
    {"name": "Celesteela", "dexNum": 797},
    {"name": "Kartana", "dexNum": 798},
    {"name": "Guzzlord", "dexNum": 799},
    {"name": "Necrozma", "dexNum": 800},
    {"name": "Poipole", "dexNum": 803},
    {"name": "Naganadel", "dexNum": 804},
    {"name": "Stakataka", "dexNum": 805},
    {"name": "Blacephalon", "dexNum": 806},
    {"name": "Zacian", "dexNum": 888},
    {"name": "Zamazenta", "dexNum": 889},
    {"name": "Eternatus", "dexNum": 890},
    {"name": "Kubfu", "dexNum": 891},
    {"name": "Urshifu", "dexNum": 892},
    {"name": "Regieleki", "dexNum": 894},
    {"name": "Regidrago", "dexNum": 895},
    {"name": "Glastrier", "dexNum": 896},
    {"name": "Spectrier", "dexNum": 897},
    {"name": "Calyrex", "dexNum": 898},
    {"name": "Enamorus", "dexNum": 905},
    {"name": "Wo-Chien", "dexNum": 1001},
    {"name": "Chien-Pao", "dexNum": 1002},
    {"name": "Ting-Lu", "dexNum": 1003},
    {"name": "Chi-Yu", "dexNum": 1004},
    {"name": "Koraidon", "dexNum": 1007},
    {"name": "Miraidon", "dexNum": 1008},
    {"name": "Ondulagua", "dexNum": 1009},
    {"name": "Ferroverdor", "dexNum": 1010},
    {"name": "Flamariete", "dexNum": 1020},
    {"name": "Electrofuria", "dexNum": 1021},
    {"name": "Ferromole", "dexNum": 1022},
    {"name": "Ferrotesta", "dexNum": 1023},
    {"name": "Terapagos", "dexNum": 1024},
    {"name": "Pecharunt", "dexNum": 1025}
        
    ],
    /* Tier 6 */ [
    {"name": "Mew", "dexNum": 151},
    {"name": "Celebi", "dexNum": 251},
    {"name": "Jirachi", "dexNum": 385},
    {"name": "Deoxys", "dexNum": 386},
    {"name": "Phione", "dexNum": 489},
    {"name": "Manaphy", "dexNum": 490},
    {"name": "Darkrai", "dexNum": 491},
    {"name": "Shaymin", "dexNum": 492},
    {"name": "Arceus", "dexNum": 493},
    {"name": "Victini", "dexNum": 494},
    {"name": "Keldeo", "dexNum": 647},
    {"name": "Meloetta", "dexNum": 648},
    {"name": "Genesect", "dexNum": 649},
    {"name": "Diancie", "dexNum": 719},
    {"name": "Hoopa", "dexNum": 720},
    {"name": "Volcanion", "dexNum": 721},
    {"name": "Magearna", "dexNum": 801},
    {"name": "Marshadow", "dexNum": 802},
    {"name": "Zeraora", "dexNum": 807},
    {"name": "Meltan", "dexNum": 808},
    {"name": "Melmetal", "dexNum": 809},
    {"name": "Zarude", "dexNum": 893},
    {"name": "Pecharunt", "dexNum": 1025}
]
];